[[redirects]]
  from = "/blog/prompt-frameworks-unlock-the-full-power-of-chatgpt/"
  to = "/blog/prompt-frameworks-vs-prompts-collection/"
  status = 301

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "alekspetrov"
  deliveryType = "upload"
  imagesPath = "/images"