[[redirects]]
  from = "/blog/prompt-frameworks-unlock-the-full-power-of-chatgpt/"
  to = "/blog/prompt-frameworks-vs-prompts-collection/"
  status = 301

[[redirects]]
  from = "/refound/"
  to = "/refund/"
  status = 301

[[redirects]]
  from = "/blog/blank/"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/release-notes/"
  to = "/blog/how-ai-is-transforming-content-creation/"
  status = 301

[[redirects]]
  from = "/release-notes"
  to = "/blog/how-ai-is-transforming-content-creation/"
  status = 301

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy/"
  status = 301

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy/"
  status = 301

[[redirects]]
  from = "/terms-of-service/"
  to = "/terms/"
  status = 301

[[redirects]]
  from = "/terms-of-service"
  to = "/terms/"
  status = 301

[[redirects]]
  from = "/features/"
  to = "/"
  status = 301

[[redirects]]
  from = "/features"
  to = "/"
  status = 301

[[redirects]]
  from = "/~partytown/"
  to = "/"
  status = 301

[[redirects]]
  from = "/tools/letter-writer-tool/"
  to = "/tools/letter-writer/"
  status = 301

[[redirects]]
  from = "/tools/paraphrizer-tool"
  to = "/tools/paraphrasing-tool/"
  status = 301

[[redirects]]
  from = "/usecases/"
  to = "/"
  status = 302

[[redirects]]
  from = "/documentation/"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/documentation"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/contacts/"
  to = "/"
  status = 302

[[redirects]]
  from = "/contacts"
  to = "/"
  status = 302

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "alekspetrov"
  deliveryType = "upload"
  imagesPath = "/images"